spring.application.name=backend

server.port=9090

spring.datasource.url=jdbc:postgresql://ep-patient-dew-aqqjo79h-pooler.c-8.us-east-1.aws.neon.tech/school_db?sslmode=require&channel_binding=require

spring.datasource.username=neondb_owner

spring.datasource.password=npg_OB9DYlgMA0JL

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true